[package]
name = "cq"
version = "0.1.0"
edition = "2024"


[dependencies]
ark-ff = "0.5.0"
ark-poly = "0.5.0"
ark-ec = "0.5.0"
ark-std = "0.5.0"
sha3 = "0.10.8"
fk = { git = "https://github.com/geometryresearch/fk", rev = "91143a8" }

[dev-dependencies]
ark-bn254 = "0.5.0"
rand_chacha = { version = "0.9.0", default-features = false }

[features]
debug = []
sanity = []

